---
language: python

branches:
  only:
    - master

env:
  global:
    # Software versions
    - TERRAFORM_VERSION=0.15.3
    - TF_VAR_cluster_name=$(uuidgen -t)
    - TF_VAR_public_net_name="public"
    - TF_VAR_image_name="ubuntu-18.04-docker-x86_64"
    - TF_VAR_master_flavor_name="m1.small"
    - TF_VAR_worker_flavor_name="m1.small"
  jobs:
    - TF_VAR_master_count=1
      TF_VAR_worker_count=1

install:
  - travis_retry curl -L
    "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
    -o /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/local/bin
  - sudo chmod +x /usr/local/bin/terraform
  - mkdir -p "$HOME/.terraform.d/plugins/"
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add

before_script:
  - terraform init
  - terraform validate
  - terraform fmt -check=true -diff

script:
  - set -o pipefail
  - terraform apply -auto-approve | grep -v remote-exec
  - export TF_VAR_worker_count=$((TF_VAR_worker_count+1))
  - terraform apply -auto-approve | grep -v remote-exec
  - export TF_VAR_worker_count=$((TF_VAR_worker_count-1))
  - terraform apply -auto-approve | grep -v remote-exec

after_script:
  - terraform destroy -auto-approve

